config/routes.rb
Rails.application.routes.draw do

  

  root 'public#index'

  get 'admin', :to =>"access#index"
  

  resources :subjects
  resources :pages
    
 
  resources :sections do

      resources :comments 

        

      

  end

  resources :admin_users
  
   
  match ':controller(/:action(/:id))', via: [:get,:post]

 

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'admin'
   
   
   before_action :validate_user, :except=>[:login, :attempt_login,:logout]
   before_action :find_subject

  def index

   


  end

  

    
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/index.html.erb
<%= @page_title="Admin Page" %>

<div class ="menu">
	<h2> Welcome to admin page </h2>


    <ul>
  
        <li><%= link_to("ADD Content",subjects_path) %></li>
        
	<li><%= link_to("Logout",:action=> "logout") %></li>
        <li><%= link_to("Go to Admin Page", admin_users_path) %></li>
   </ul>

  
</div>

app/views/access/login.html.erb
<h2> Welcome to admin Page</h2>




<div class="login">
  
  <%= form_tag(:action=>"attempt_login" ) do %>
    <table>
     <p> Please login to enter </p>
    <tr>
      <td> <%= label_tag(:username, "Username") %> </td>
      <td><%= text_field_tag(:username) %> </td>
    </tr>
     
    <tr>
      <td> <%= label_tag(:password, "Password") %> </td>
      <td> <%= password_field_tag(:password) %> </td>
     </tr>
     
     <tr>
       <td><%= submit_tag("Submit") %></td>
     </tr>


  <% end %>
  </table>

</div>