config/routes.rb
Rails.application.routes.draw do

  

  root 'public#index'

  get 'admin', :to =>"access#index"
  

  resources :subjects
  resources :pages
    
 
  resources :sections do

      resources :comments 

        

      

  end

  resources :admin_users
  
   
  match ':controller(/:action(/:id))', via: [:get,:post]

 

end

app/models/section.rb
class Section < ActiveRecord::Base
    
    belongs_to :page
    has_many :section_edits
    has_many :comments

   
    has_many :editors, :through=> :section_edits, :class_name=>"AdminUser"

  scope :sorted, lambda{order('created_at DESC')}

   scope :visible, lambda{where(:visible=>true)}


has_attached_file :image, :styles => {:medium => "300x300"}
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController


 layout 'admin'
 before_action :find_page

def index
 if @subject
 @sections = @page.sections.sorted

  else
   @sections = Section.all
  end

 end

def show
  
  @section = Section.find(params[:id])
  @comments = Comments.where(section_id:@section)

end


def new

   @section = Section.new({ :name => "Default"})
   @pages = Page.all
   @section_count = Section.count + 1
   
end

def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section created successfully."
      redirect_to(:action => 'index')
    else
      @pages = @page.subject.pages.sorted
      @section_count = Section.count + 1
      render('new')
    end
  end


def show

  @section = Section.find(params[:id])

end


def  edit
  
  @section = Section.find(params[:id])
  @pages = Page.all
  @section_count = Section.count + 1


end


def update

  @section = Section.find(params[:id])
  @pages = Page.all

   if @section.update_attributes(section_params)


	   flash[:notice]= "Updated Succesfully"

	   redirect_to ({action: :index})
           @section_count = Section.count + 1

     else
         
         

	   redirect_to 'edit'
    
     end


end


def delete

 @section = Section.find(params[:id])


end

def destroy

   @section = Section.find(params[:id]).destroy

   flash[:notice]= "Deleted Successfully"

   redirect_to ({action: :index})


end



private

  def section_params

    params.require(:section).permit(:page_id,:name,:position,:visible,:image,:content_type,:content)
   end


 def find_page

    if params[:page_id] 
     @page = Page.find(params[:page_id])
    end
   

  end



end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= error_messages_for(@section) %>

<table summary="Section form fields">
  <tr>
    <th><%= f.label(:page_id, "Page") %></th>
    <td><%= f.select(:page_id, @pages.collect {|p| [p.name, p.id]}) %>
</td>
  </tr>
  <tr>
    <th><%= f.label(:name) %></th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:position) %></th>
    <td><%= f.select(:position,1..@section_count) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible) %></th>
    <td><%= f.check_box(:visible) %></td>
  </tr>

  <tr>
    <th><%= f.label(:image,"Upload Image") %></th>
    <td><%= f.file_field :image %> </td>
  </tr>
  <tr>
    <th><%= f.label(:content_type) %></th>
    <td>
      <%= f.radio_button(:content_type, 'text') %> Text
      <%= f.radio_button(:content_type, 'HTML') %> HTML
    </td>
  </tr>
  <tr>
    <th><%= f.label(:content) %></th>
    <td><%= f.text_area(:content, :size => '40x10') %></td>
  </tr>
</table>

app/views/sections/edit.html.erb
<h1> Update Page</h1>


<%= form_for(@section,:id=>@section.id) do |f| %>
  
 <%= render 'form', f:f %>

  <%= f.submit("Update Page") %>



<% end %>

app/views/sections/index.html.erb
<div class ="sections index">

<h1>Sections</h1>

  <% if @subject %>

  <%= link_to("Add new Section",{action: :new,:page_id=>@page.id}, class:"action new") %>

  <% else %>

   <%= link_to("Add new Section",{action: :new}, class:"action new") %>
   <% end %>
<% if @sections.size > 0 %>

  <table class ="listing" summary="Subject list" >

      <tr class ="header">

         <th>&nbsp;</th>
         <th> Name </th>
         <th>Visible</th>
         <th> Content Type</th>
         <th>Content</th>
         <th>Action</th>
  

       </tr>
          
         <% @sections.each do |section| %>


       <tr class="<%= cycle('odd', 'even') %>">
         
           <td><%= section.position %></td>
           <td><%= section.name %></td>
           <td class="center"><%= section.visible ? 'Yes' : 'No' %></td>
           <td><%= section.content_type %></td>
           <td><%= section.content %></td>
           
           <td class="actions">
            <%if @subject %>
                <%= link_to("Show",{action: :show,id:section.id,page_id:@page.id}, :class=>"action show") %>
                <%= link_to("Edit",{action: :edit,id:section.id,page_id:@page.id}, :class=>"action edit") %>
                <%= link_to("Destroy",section_path(section), method: :delete,data: {confirm: "Are you sure?"},:class=>"action delete") %>
            <%else %>

               <%= link_to("Show",{action: :show,id:section.id}, :class=>"action show") %>
                <%= link_to("Edit",{action: :edit,id:section.id}, :class=>"action edit") %>
                <%= link_to("Destroy",section_path(section),method: :delete,data: {confirm: "Are you sure?"},:class=>"action delete") %>
            <% end %>

            </td>
          

       </tr>

       <% end %>

 </table>

<% else %>

   <h2> There is no subject to show </h2>


<% end %>

</div>

app/views/sections/new.html.erb
<% @page_title = "New Section" %>


<div class="sections new">
  <h2>Create Section</h2>

  <%= form_for @section,:html => { :multipart => true }  do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= submit_tag("Create Section") %>
    </div>

  <% end %>
</div>

app/views/sections/show.html.erb
<% if !flash.blank? %>

   <div id = "flash-notice">
     
      <%= flash[:notice] %>

   </div>

<% end %>



<div >

  <h2> Here is the information of subject : <%= @section.name %> </h2>

  <table>

   <tr>
     
    <th> Section Name : </th>
    <td> <%= @section.name %> </td>

   </tr>
   
  <tr>
     
    <th> Position </th>
    <td> <%= @section.position %> </td>

   </tr>

  <tr>
     
    <th> Visible :</th>
    <td> <%= @section.visible ? 'Yes' : 'No' %> </td>

   </tr>

  <tr>
     
    <th>  Content Type : </th>
    <td> <%= @section.content_type %> </td>

   </tr>

   <tr>
     
    <th>  Content  : </th>
    <td> <%= @section.content %> </td>

   </tr>






  </table>

<h5><%= link_to("<<Back to Home Page", {action: :index}) %> </h3>




</div>