config/routes.rb
Rails.application.routes.draw do

  

  root 'public#index'

  get 'admin', :to =>"access#index"
  

  resources :subjects
  resources :pages
    
 
  resources :sections do

      resources :comments 

        

      

  end

  resources :admin_users
  
   
  match ':controller(/:action(/:id))', via: [:get,:post]

 

end

app/views/pages/_form.html.erb
<%= error_messages_for(@page) %>

<div class ="field"> 
   <%= f.label(:subject_id, "Subjects") %>
   <%= f.select(:subject_id,@subjects.map{|s|[s.name,s.id]}) %>
  </div>


<div class ="field"> 
   <%= f.label(:name, "Name") %>
   <%= f.text_field(:name) %>
  </div>
 
  <div class="field"> 
   <%= f.label(:position, "Position") %>
   <%= f.select(:position,1..@page_count) %>
  </div>

   <div class ="field" > 
   <%= f.label(:permalink, "Permalink") %>
   <%= f.text_field(:permalink) %>
  </div>

 

  <div class ="field" > 
   <%= f.label(:visible, "Visible") %>
   <%= f.check_box(:visible) %>
  </div>

 

app/views/pages/delete.html.erb
<%= form_for(:page, url:{action: :destroy, id: @page.id}) do |f| %>
  
   <p> Are you sure , you want to delete the page? </p>
   <p> <%= @page.name %> </p>
 
 
<div >
  <%= f.submit("Yes, Delete Page") %>
</div>

<h5><%= link_to("<<Back to Home Page", {action: :index}) %> </h3>


<% end %>

app/views/pages/edit.html.erb
<h1> Update Page</h1>


<%= form_for(@page, id:@page.id) do |f| %>
  
      <%= render(partial:"form",locals:{f:f}) %>

  <%= f.submit("Update Page") %>



<% end %>

app/views/pages/index.html.erb
<div class ="pages index">

<h1>Pages</h1>
  <% if @subject.present? %>
  <%= link_to("Add new Page",{action: :new,:subject_id => @subject.id }, class:"action new") %>
 <% else %>
    <%= link_to("Add new Page",{action: :new}, class:"action new") %>
<% end %>
<% if @pages.size > 0 %>

  <table class ="listing" summary="Subject list" >

      <tr class ="header">

         <th>&nbsp;</th>
         <th>Page </th>
         <th>Visible</th>
         <th> Sections </th>
         <th>Actions </th>


       </tr>
          
         <% @pages.each do |page| %>


       <tr>

           <td><%= page.position %></td>
           <td><%= page.name %></td>
           <td "><%= status_tag(page.visible ? 'Yes' : 'No') %></td>
           <td class="center"><%= page.sections.size %></td>
           <td class="actions">

          <% if @subject.present? %>
              <%= link_to("View Sections",sections_path(:page_id=>page.id, :subject_id=>@subject.id), :class=>"action show")%>
                <%= link_to("Show",{action: :show,id:page.id,:subject_id => @subject.id}, :class=>"action show") %>
                <%= link_to("Edit",{action: :edit,id:page.id,:subject_id => @subject.id}, :class=>"action edit") %>
                <%= link_to("Delete",page_path(id:page.id,:subject_id => @subject.id),confirm: "Are you sure?", method: :delete, :class=>"action delete") %>

         <% else %>
             <%= link_to("View Sections",sections_path(:page_id=>page.id), :class=>"action show")%>
                <%= link_to("Show",{action: :show,id:page.id}, :class=>"action show") %>
                <%= link_to("Edit",{action: :edit,id:page.id}, :class=>"action edit") %>
                <%= link_to("Delete",page_path(id:page.id),confirm: "Are you sure?", method: :delete, :class=>"action delete") %>

        <% end %>

            </td>
          

       </tr>

       <% end %>

 </table>

<% else %>

   <h2> There is no Page to show </h2>


<% end %>

</div>

app/views/pages/new.html.erb
<h1> Create New Subject </h1>

<% if @subject %>
<%= form_for(:page, :url => {:action => 'create', :subject_id => @subject.id}) do |f| %>

<%= render(:partial => "form", :locals => {:f => f}) %>

  
 
  
  

<%= submit_tag("Create Page") %>

<% end %>
 

<% else %>

<%= form_for(:page, :url => {:action => 'create'}) do |f| %>

<%= render(:partial => "form", :locals => {:f => f}) %>

  
 
  
  

<%= submit_tag("Create Page") %>

<% end %>

<% end %>

app/views/pages/show.html.erb
<% if !flash.blank? %>

   <div id = "flash-notice">
     
      <%= flash[:notice] %>

   </div>

<% end %>



<div >

  <h2> Here is the information of subject : <%= @page.name %> </h2>

  <table>

   <tr>
     
    <th>Page Name : </th>
    <td> <%= @page.name %> </td>

   </tr>
   
  <tr>
     
    <th> Position </th>
    <td> <%= @page.position %> </td>

   </tr>

  <tr>
     
    <th> Visible :</th>
    <td> <%= @page.visible ? 'Yes' : 'No' %> </td>

   </tr>

  <tr>
     
    <th>  Pages : </th>
    <td> <%= @page.sections.size %> </td>

   </tr>





  </table>

<h5><%= link_to("<<Back to Home Page", {action: :index}) %> </h3>




</div>